name: Check Bot Code Quality 

on:
  push:
    paths: ["bot/**"]
    branches: ["*"]
  pull_request:
    paths: ["bot/**"]
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          cd bot
          npm install

      - name: Build Site
        run: |
          cd bot
          npx eslint .
          
